### PR TITLE
Allow adding a incremented number in each occurence

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
at any place.

* iedit-lib.el (iedit-increment-occurences): New.
(iedit-occurrence-keymap-default): Bind it.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
This works like this:
Say you want to transform the fooz below to fooz-001 002 etc...
fooz
fooz
fooz 
Start iedit-mode with cursor on fooz, add `-\#` at end and hit `M-V`, you have now:
fooz-001
fooz-002
fooz-003
You can add `\#` at any place in the string.
This is useful for example to quickly rename files from wdired.
I used '\#' because it is same as what use replace-regexp.

**Comment by thierryvolpiatto** [comment]
Perhaps the function name can be changed and the binding `M-V` as well, didn't have better idea.
Thanks.

**Comment by thierryvolpiatto** [comment]
Using this function in `iedit-rect-keymap` is also useful.

**Comment by thierryvolpiatto** [comment]
iedit-increment

**Comment by thierryvolpiatto** [comment]
Peek 14-06-2020 16-24

**Comment by thierryvolpiatto** [comment]
Ping...

**Comment by victorhge** [comment]
Nice feature.  Merged in first.

**Comment by thierryvolpiatto** [comment]
Victor Ren <notifications@github.com> writes:

> Nice feature. Merged in first.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Pull request merged**
