### PR TITLE
Allow custom iedit-regexp-quote function

### PR DESCRIPTION
**Pull request by justbur**

### CODE REVIEW

**Comment by victorhge** [comment]
Would you describe the use case of the option?

**Comment by justbur** [comment]
I'm extending iedit in another package and am having to work around this
function by advising it. I thought adding the flexibility to specify a
different function might be useful to someone else at some point. It's not
critical that you merge this though since the advice is working fine for
me.

**Comment by victorhge** [comment]
In the lastest commit, `iedit-regexp-quote' is the same as the one in your evil-iedit.   You don't have to advising it or make it customizable.  

I think this pull request can be closed.

**Comment by justbur** [comment]
Oh, nice. Thank you. 

By the way, I was thinking that most of what I was doing there was not specific to evil and could go into iedit itself. I was really trying to come up with a minimal extension of iedit that would work nicely with evil.

**Pull request closed without merging**
